version: '3'
networks:
  nrv.net:
    driver: bridge
services:

  nrv.api:
    image: 'canals/php:latest'
    ports:
      - '2080:80'
      - '1443:443'
    volumes:
      - ../API/public:/var/www/html
      - ../API:/var/www
    working_dir: /var/www/
    networks:
      nrv.net:
        aliases:
          - api.nrv.local
    depends_on:
      - nrv.db

  nrv.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: db.env
    ports:
      - '3307:3306'
    networks:
      - nrv.net

  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - nrv.net